trigger:
- main

variables:
- group: Az-DevOps-Pipelines

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    terraform init \
      -backend-config="storage_account_name=$TF_STATE_BLOB_ACCOUNT_NAME" \
      -backend-config="container_name=$TF_STATE_BLOB_CONTAINER_NAME" \
      -backend-config="key=$TF_STATE_BLOB_FILE" \
      -backend-config="access_key=$TF_STATE_STORAGE_KEY"
  displayName: Terraform Init
  env:
    TF_STATE_BLOB_ACCOUNT_NAME:   $(storage-account-name)
    TF_STATE_BLOB_CONTAINER_NAME: $(container-name)
    TF_STATE_BLOB_FILE:           $(TFstate-File-Name)
    TF_STATE_STORAGE_KEY:      $(euterraformstatefile-key-1)   
- bash: terraform plan -out deployment.tfplan
  displayName: Terraform Plan 
  env:
    ARM_SUBSCRIPTION_ID: $(kv-arm-subscription-id)
    ARM_CLIENT_ID:       $(kv-arm-client-id)
    ARM_CLIENT_SECRET:   $(kv-arm-client-secret)
    ARM_TENANT_ID:       $(kv-arm-tenant-id)
- bash: terraform apply -auto-approve deployment.tfplan
  displayName: Terraform Apply
  env:
    ARM_SUBSCRIPTION_ID: $(kv-arm-subscription-id)
    ARM_CLIENT_ID:       $(kv-arm-client-id)
    ARM_CLIENT_SECRET:   $(kv-arm-client-secret)
    ARM_TENANT_ID:       $(kv-arm-tenant-id)